### ISSUE TITLE
Format des erreurs de compilation

### ISSUE THREAD

**Issue by VLanvin** [ogaml/ogaml#12]
Actuellement, lorsqu'un programme GLSL renvoie une erreur de compilation, on raise une exception avec comme argument le log contenant l'erreur.
Le problème c'est que la chaîne est automatiquement "escaped", donc la mise en forme est illisible (avec des \n visibles partout).
Il faut donc trouver une solution à ça : 
- Soit on fournit un système de log, et on l'utilise pour créer une espèce de "stderr" qui contiendrait ce genre de choses, dans ce cas l'exception renverrait juste le message "see stderr for more info"
- Soit on laisse à l'utilisateur le soin de matcher l'exception, d'appeler Scanf.unescaped et d'afficher l'erreur
- Soit on affiche l'erreur dans le terminal (ou un log) sans pour autant fournir un système de log complet

**Comment by TheoWinterhalter** [comment]
Dans tous les cas il me paraît raisonnable d'afficher un truc dans le terminal (que se passe-t-il si on décide de faire une application en mode fenêtrée qui ne passe plus par le terminal par contre ?).

Ça peut être pas mal si l'utilisateur peut le paramétrer donc soit avec un système de log (qui permet de rediriger dans fichier ou d'afficher et rediriger par exemple) soit juste en exposant une fonction de window (puisqu'elle gère le contexte openGL) qui propose le choix.

**Comment by VLanvin** [comment]
Pour finir, j'ai implémenté un système de log, mais j'ai préféré laisser le choix à l'utilisateur de gérer l'exception lui-même. 
Je pense que, selon les circonstances, l'utilisateur pourrait vouloir appeler Log.fatal, Log.error ou Log.debug. Il me semblait donc un peu trop restrictif que Program appelle log par lui-même.
L'exception est toujours escaped donc, et est par défaut renvoyée sur le terminal (si l'utilisateur décide de ne pas la rattraper pour log le message).

**Comment by VLanvin** [comment]
Le log peut-être passé en paramètre optionnel à Program.create désormais. En l'absence de log, Program.create lève une exception sans précisions supplémentaires.
