### ISSUE TITLE
Interface ogamlWindow.mli (suivi)

### ISSUE THREAD

**Issue by VLanvin** [ogaml/ogaml#2]
J'ai push une première version de l'interface commune (multi-platforme) de la gestion des fenêtres et des évènements. Pour l'instant, elle requiert seulement des fonctions de base sur les fenêtres (création, fermeture, destruction), ainsi que la détection des évènements de base.

Pour la première version, dans un souci de simplicité, les évènements ne sont qu'une énumération sans argument, on ne peut par exemple pas savoir quelle touche a été appuyée lors d'un évènement KeyPressed.

Les différents fichiers (ogamlWindow_xlib.ml, ogamlWindow_cocoa.ml, etc...) devront implémenter exactement cette interface.

**Comment by VLanvin** [comment]
J'ajoute juste quelques idées concernant la nouvelle interface openGL/window. 

L'idée serait d'avoir directement les fonctions d'affichage dans le module Window, et de cacher la structure `State.t` (représentant l'état openGL) dans la structure `Window.t`.

Concrètement, on aurait des fonctions du type : 

`Window.draw3D : Window.t -> VertexArray.t -> Program.t -> Uniform.t list -> DrawParameter.t list -> unit`

`Window.draw2D : Window.t -> Texture.t -> Sprite.t -> unit`

ce qui permet de cacher toute la "mutabilité" du contexte, tout en permettant d'optimiser les changements d'état.

Ici, Uniform.t est une disjonction de tous les paramètres de programme possibles, DrawParameter.t une disjonction de tous les paramètres d'affichage possibles (`CullingMode.t`, `PolygonMode.t`, etc). 
Reste à savoir comment coder joliment ces disjonctions (variant ? polymorphe ?), sans que ce soit trop lourd syntaxiquement.

Une autre solution serait de définir DrawParameter.t comme un record immutable contenant la valeur des différents paramètres d'affichage, on aurait alors (où la plupart des paramètres sont optionnels) : 

`let params = DrawParameter.create CullingMode.CullNone PolygonMode.DrawFill`
`Window.draw3D win vao prog uniforms params`

Concernant les Uniform.t, il pourrait aussi être possible de cacher le type à l'utilisateur, et fournir des fonctions (typées) de création, pour donner une syntaxe comme : 

`let uniforms_list = Uniform.([matrix3D my_mat; vector2f my_vec; float 5.])`

**Comment by TheoWinterhalter** [comment]
On peut aussi imaginer des fonctions pour créer les paramètres avec des labels. Je préfère ça à des structs (enfin, même si ce sont des structs des *helpers* pour les créer ça peut être sympa), plus facile à *inliner*.

**Comment by VLanvin** [comment]
Oui je suis tout à fait d'accord pour les labels, je ne les avais pas mis pour simplifier la notation. Ca marche bien pour DrawParameter car il ne peut y avoir qu'un de chaque, et ça permet en plus de définir directement les valeurs par défaut (avec des labels optionnels).

En revanche, pour Uniform c'est plus dur, car il peut y avoir plusieurs uniforms du même type. Donc je pencherais plutôt pour la dernière syntaxe, celle avec des helpers. D'ailleurs j'ai oublié un détail, c'est qu'il faut aussi passer des chaînes en argument, donc ça donnerait plutôt : 

`Uniform.([matrix3D "foo" my_foo; matrix3D "bar" my_bar])`

Sinon, plutôt que d'encapsuler les paramètres dans DrawParameter.t, on peut aussi directement les passer à Window.draw avec des labels optionnels, mais ça risque de faire une fonction à 15 arguments (minimum)... L'autre avantage d'encapsuler tout ça c'est qu'il est facile de détecter et d'optimiser le changement d'état si on appelle deux fois draw avec le même groupe de paramètres.

**Comment by VLanvin** [comment]
La partie GL est quasiment finie maintenant, et j'ai encapsulé State dans Window. Cependant, il y a un endroit où ça coince un peu, car la partie binding et la partie exposée de Window sont trop entrelacées. De plus, il faut avouer que la partie Window (côté X11) est assez horrible, notamment à cause de la manipulation du préprocesseur. 

Pour régler ce problème, l'idée serait de retravailler un peu la structure globale du projet : 
* Toute la partie OgamlWindow devient OgamlCore, et n'est plus utilisée pour créer des fenêtres (à part en interne). Elle contiendrait les events, et l'interface commune (sans appels openGL) de fenêtre. On revient à la compilation en pack (plus propre), et les implémentations window_impl, mouse_impl et keyboard_impl sont toutes encapsulées dans un module Internal.
* Les parties OgamlGL et Ogaml2D fusionnent pour donner OgamlGraphics (?), elles ne sont pas si différentes après tout. OgamlGraphics introduit un nouveau module de fenêtre qui encapsule OgamlWindow.Internal, ainsi que les appels openGL. 

Avec cette nouvelle structure, toutes les fonctions utilisant openGL sont rangées dans le même module, plutôt que réparties sur 3 modules.

**Comment by TheoWinterhalter** [comment]
Okay oui, c'est sans doute plus simple à utiliser comme ça. :+1:

**Comment by VLanvin** [comment]
Bon je pense que cette issue peut être fermée, l'interface est plus ou moins stable maintenant. :-)
