### ISSUE TITLE
Commentaires sur OgamlUtils.Graph

### ISSUE THREAD

**Issue by OlivierMarty** [ogaml/ogaml#27]
Pourquoi ce module ?

Je crois que :
 - bfs et dfs parcourent uniquement les sommets accessibles contrairement à ce que la doc dit ;
 - remove_vertex ne supprime pas les arêtes entrantes ;
 - les arêtes devraient être de type arbitraire (avec zero, inf, plus, compare...) ;
 - neighbours devrait être un itérateur.

Sinon [ocamlgraph](http://ocamlgraph.lri.fr/index.en.html) est très bien fait !

**Comment by TheoWinterhalter** [comment]
Dans la philosophie d'ogaml on essaie de limiter les dépendances au maximum.
Entre autre, les binaires sont facilement distribuables.
Bon par contre je sais pas pourquoi on a ça, Victor a dû en avoir besoin dans l'un de ses projets.

**Comment by VLanvin** [comment]
Sachant que Ogaml a pour but d'être un framework (relativement) complet pour développer jeux et applications graphiques, j'y ajoute un peu tout ce dont j'ai besoin pour mes projets, dont les algos de graphes.
Je suis d'accord que ocamlgraph est particulièrement bien fait, et OgamlUtils.Graph n'a pas pour ambition de faire mieux. Le type qui découvre OCaml et qui a envie de faire un petit jeu n'a peut-être pas envie de se taper un triple foncteur pour faire un A* et déplacer son personnage sur une grille (ce qui était plus ou moins mon cas). Après, si il a besoin de graphes plus modulaires, rien ne l'empêche d'utiliser ocamlgraph.
J'aurais même préféré pouvoir me passer du foncteur sur les vertices, mais ça aurait manqué cruellement de souplesse.

Pour tes points : 

  * Effectivement, c'est peut-être plus un problème de doc que de code pour le coup.

  * My bad pour remove_vertex, j'ai du coder ça à la va-vite.

  * Voir mon explication précédente.

  * Tu veux dire `val neighbours : t -> vertex -> (vertex -> unit) -> unit` ? Ou vraiment `t -> vertex -> vertex iterator` ?

**Comment by OlivierMarty** [comment]
OK, ça fait sens.
Je veux dire ```val neighbours : t -> vertex -> (vertex -> unit) -> unit```.
